import "./globals.css";

export const metadata = {
  title: "LQ458 Personal Website",
  description: "Generated by LQ458",
};

export default function RootLayout({ children }) {
  return <html lang="en">{children}</html>;
}
