import "./globals.css";
import "typeface-dosis";
import "typeface-poppins";

export const metadata = {
  title: "Yihao Qin's Personal Website",
  description: "Generated by LQ458",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
